import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import path from "path";
import { fileURLToPath } from "url";

import connectDB from "./src/db/connectDB.js";
import userRoutes from "./src/routes/userRoutes.js";
import companyRoutes from "./src/routes/companyRoutes.js";
import jobRoutes from "./src/routes/jobRoutes.js";
import Cloudinary from "./src/utils/Cloudinary.js";

// ============================================================
// PATH CONFIGURATION
// ============================================================

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ============================================================
// ENVIRONMENT VARIABLES
// ============================================================

// Local development:
// Loads variables from backend/.env
//
// Production (GoDaddy):
// GoDaddy's environment variables will be used automatically.

dotenv.config({
  path: path.join(__dirname, ".env"),
});

// ============================================================
// EXPRESS APP
// ============================================================

const app = express();

// ============================================================
// FRONTEND PATH
// ============================================================

// server.js is inside:
// backend/server.js
//
// React production build is inside:
// frontend/dist
//
// Therefore ../frontend/dist is the correct path.

const frontendPath = path.join(__dirname, "../frontend/dist");

// ============================================================
// MIDDLEWARE
// ============================================================

// Allow frontend/API requests
app.use(cors());

// Parse JSON request bodies
app.use(express.json());

// Parse URL-encoded request bodies
app.use(express.urlencoded({ extended: true }));

// ============================================================
// DATABASE & CLOUDINARY
// ============================================================

connectDB();
Cloudinary();

// ============================================================
// API TEST
// ============================================================

app.get("/api", (req, res) => {
  res.json({
    success: true,
    message: "Kawakami Overseas Placements API is working",
  });
});

// ============================================================
// API ROUTES
// ============================================================

app.use("/user", userRoutes);
app.use("/company", companyRoutes);
app.use("/job", jobRoutes);

// ============================================================
// SERVE REACT FRONTEND
// ============================================================

// Serve files generated by:
// npm run build
//
// from:
// frontend/dist

app.use(express.static(frontendPath));

// ============================================================
// REACT SPA FALLBACK
// ============================================================

// If the request is not an API request,
// send React's index.html.
//
// This allows routes such as:
//
// /about
// /services
// /contact
// /candidate-login
// /recruiter-login
// etc.
//
// to work correctly after deployment.

app.use((req, res, next) => {
  if (req.method !== "GET") {
    return next();
  }

  // Never send React index.html for API routes
  if (req.path.startsWith("/user")) {
    return next();
  }

  if (req.path.startsWith("/company")) {
    return next();
  }

  if (req.path.startsWith("/job")) {
    return next();
  }

  if (req.path.startsWith("/api")) {
    return next();
  }

  // Send React application
  res.sendFile(path.join(frontendPath, "index.html"));
});

// ============================================================
// SERVER
// ============================================================

// GoDaddy provides process.env.PORT in production.
// 5000 is used locally if PORT isn't defined.

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`🌐 Server is running on port ${PORT}`);
});